### ISSUE TITLE
FamStruct safe wrappers don't implement clone

### ISSUE THREAD

**Issue by acatangiu** [rust-vmm/kvm-bindings#12]
The `FamStructWrapper` safe wrapper implements `Clone` if the object it wraps also implements `Clone`.

To enable `Clone` on the safe wrappers `CpuId`, `Msrs` and `MsrList` we need to implement `Clone` for `kvm_cpuid2`, `kvm_msrs` and respectively `kvm_msr_list`.

**Comment by andreeaflorescu** [comment]
Should we close this one now?

**Comment by acatangiu** [comment]
Fixed in https://github.com/rust-vmm/vmm-sys-util/pull/55
