### ISSUE TITLE
Experimental riscv64 support

### ISSUE THREAD

**Issue by rbradford** [rust-vmm/kvm-bindings#80]
Following on from a Slack conversation. Here is the outline for enabling riscv64 support here:

- [x] Update KVM bindings for aarch64 / x86-64 to latest released kernel
- [ ] Generate riscv64 bindings from same kernel
- [ ] Add basic cross compilation testing - probably using GitHub actions as I don't think rust-vmm-ci is cross aware.

**Comment by roypat** [comment]
Closing this as completed by #160. We've updated our bindings to 6.9, added riscv64 bindings from the same kernel, and are doing testing (both compilation and unit tests) via qemu-system-riscv64
